/*
 * This file was automatically generated by SmartUnit
 */

package sut.com.wanxin.api.depository.model;

import org.junit.Test;
import static org.junit.Assert.*;
import java.lang.reflect.Method;
import com.wanxin.api.depository.model.DepositoryConsumerResponse;
import org.junit.runner.RunWith;
import org.smartunit.runtime.SmartRunner;
import org.smartunit.runtime.SmartRunnerParameters;

@RunWith(SmartRunner.class) @SmartRunnerParameters(mockJVMNonDeterminism = true, useVNET = true, resetStaticState = true) 
public class DepositoryConsumerResponse_SSTest extends DepositoryConsumerResponse_SSTest_scaffolding {
// allCoveredLines:[14, 17, 20]

  @Test(timeout = 9000)
  public void test_equals_0()  throws Throwable  {
      //caseID:f69afcc011f84a5d2ccdc0f68c0c831d
      //CoveredLines: [14, 14, 14, 14, 14, 14, 14]
      //Input_0_Object: )
      //Assert: assertFalse(method_result);
      
      DepositoryConsumerResponse depositoryConsumerResponse0 = new DepositoryConsumerResponse();
      
      //Call method: equals
      boolean boolean0 = depositoryConsumerResponse0.equals(")");
      
      //Test Result Assert
      assertFalse(boolean0);
  }

  @Test(timeout = 9000)
  public void test_equals_1()  throws Throwable  {
      //caseID:00bdc9ca85ed76b0d687e61afcdf7f4e
      //CoveredLines: [14, 14, 14, 14, 14, 14, 14]
      //Input_0_Object: depositoryConsumerResponse0
      //Assert: assertTrue(method_result);
      
      DepositoryConsumerResponse depositoryConsumerResponse0 = new DepositoryConsumerResponse();
      
      //Call method: equals
      boolean boolean0 = depositoryConsumerResponse0.equals(depositoryConsumerResponse0);
      
      //Test Result Assert
      assertTrue(boolean0);
  }

  @Test(timeout = 9000)
  public void test_equals_2()  throws Throwable  {
      //caseID:c8e44530a1100b8f5a0114d5a56739ad
      //CoveredLines: [14, 14, 14, 14, 14, 14, 14, 17, 20]
      //Input_0_Object: depositoryConsumerResponse0
      //Assert: assertTrue(method_result);
      
      DepositoryConsumerResponse depositoryConsumerResponse0 = new DepositoryConsumerResponse();
      DepositoryConsumerResponse depositoryConsumerResponse1 = new DepositoryConsumerResponse();
      
      //Call method: equals
      boolean boolean0 = depositoryConsumerResponse1.equals(depositoryConsumerResponse0);
      
      //Test Result Assert
      assertTrue(boolean0);
  }

  @Test(timeout = 9000)
  public void test_equals_3()  throws Throwable  {
      //caseID:41854c06dd0de325dff403b34f39857a
      //CoveredLines: [14, 14, 14, 14, 14, 14, 14, 17, 20]
      //Input_0_Object: depositoryConsumerResponse1
      //Assert: assertTrue(method_result);
      
      DepositoryConsumerResponse depositoryConsumerResponse0 = new DepositoryConsumerResponse();
      DepositoryConsumerResponse depositoryConsumerResponse1 = new DepositoryConsumerResponse();
      
      //Call method: equals
      boolean boolean0 = depositoryConsumerResponse0.equals(depositoryConsumerResponse1);
      
      //Test Result Assert
      assertTrue(boolean0);
  }

  @Test(timeout = 9000)
  public void test_hashCode_4()  throws Throwable  {
      //caseID:4d651ccdd9859f4390c759323b105ef2
      //CoveredLines: [14, 14, 14, 14, 14, 14, 14, 17, 20]
      
      DepositoryConsumerResponse depositoryConsumerResponse0 = new DepositoryConsumerResponse();
      
      //Call method: hashCode
      depositoryConsumerResponse0.hashCode();
  }

  @Test(timeout = 9000)
  public void test_setBankCode_5()  throws Throwable  {
      //caseID:a8c0d5543028de19aaf451345d13c908
      //CoveredLines: [14, 14, 14, 14, 14, 14, 14]
      //Input_0_String: Zlo=~e}EBQ`j
      
      DepositoryConsumerResponse depositoryConsumerResponse0 = new DepositoryConsumerResponse();
      
      //Call method: setBankCode
      depositoryConsumerResponse0.setBankCode("Zlo=~e}EBQ`j");
      
      //Test Result Assert
      assertNull(depositoryConsumerResponse0.getStatus());
  }

  @Test(timeout = 9000)
  public void test_setBankName_6()  throws Throwable  {
      //caseID:312d59970cd4f3b384096d32d080435a
      //CoveredLines: [14, 14, 14, 14, 14, 14, 14]
      //Input_0_String: X?w:u_s%{XSHe1Shl
      
      DepositoryConsumerResponse depositoryConsumerResponse0 = new DepositoryConsumerResponse();
      
      //Call method: setBankName
      depositoryConsumerResponse0.setBankName("X?w:u_s%{XSHe1Shl");
      
      //Test Result Assert
      assertNull(depositoryConsumerResponse0.getRequestNo());
  }

  @Test(timeout = 9000)
  public void test_toString_7()  throws Throwable  {
      //caseID:acf3c33a247352fb9501dff594c526a0
      //CoveredLines: [14, 14, 14, 14, 14, 14, 14, 17, 20]
      //Assert: assertEquals("DepositoryConsumerResponse(bankCode=null, bankName=null)", method_result);
      
      DepositoryConsumerResponse depositoryConsumerResponse0 = new DepositoryConsumerResponse();
      
      //Call method: toString
      String string0 = depositoryConsumerResponse0.toString();
      
      //Test Result Assert
      assertEquals("DepositoryConsumerResponse(bankCode=null, bankName=null)", string0);
  }
}
