/*
 * This file was automatically generated by SmartUnit
 */

package sut.com.wanxin.api.depository.model;

import org.junit.Test;
import static org.junit.Assert.*;
import java.lang.reflect.Method;
import com.wanxin.api.depository.model.DepositoryWithdrawResponse;
import org.junit.runner.RunWith;
import org.smartunit.runtime.SmartRunner;
import org.smartunit.runtime.SmartRunnerParameters;

@RunWith(SmartRunner.class) @SmartRunnerParameters(mockJVMNonDeterminism = true, useVNET = true, resetStaticState = true) 
public class DepositoryWithdrawResponse_SSTest extends DepositoryWithdrawResponse_SSTest_scaffolding {
// allCoveredLines:[15, 20]

  @Test(timeout = 9000)
  public void test_equals_0()  throws Throwable  {
      //caseID:1f36b201e468a81292cc34248b31dc26
      //CoveredLines: [15, 15, 15, 15, 15, 15]
      //Input_0_Object: depositoryWithdrawResponse0
      //Assert: assertTrue(method_result);
      
      DepositoryWithdrawResponse depositoryWithdrawResponse0 = new DepositoryWithdrawResponse();
      
      //Call method: equals
      boolean boolean0 = depositoryWithdrawResponse0.equals(depositoryWithdrawResponse0);
      
      //Test Result Assert
      assertTrue(boolean0);
  }

  @Test(timeout = 9000)
  public void test_equals_1()  throws Throwable  {
      //caseID:795d15d42d1959694f1a75829abe2f96
      //CoveredLines: [15, 15, 15, 15, 15, 15]
      //Input_0_Object: 1
      //Assert: assertFalse(method_result);
      
      DepositoryWithdrawResponse depositoryWithdrawResponse0 = new DepositoryWithdrawResponse();
      
      //Call method: equals
      boolean boolean0 = depositoryWithdrawResponse0.equals("1");
      
      //Test Result Assert
      assertFalse(boolean0);
  }

  @Test(timeout = 9000)
  public void test_equals_2()  throws Throwable  {
      //caseID:31bf077107218e0e92501e3f63b19edc
      //CoveredLines: [15, 15, 15, 15, 15, 15, 20]
      //Input_0_Object: depositoryWithdrawResponse0
      //Assert: assertTrue(method_result);
      
      DepositoryWithdrawResponse depositoryWithdrawResponse0 = new DepositoryWithdrawResponse();
      DepositoryWithdrawResponse depositoryWithdrawResponse1 = new DepositoryWithdrawResponse();
      
      //Call method: equals
      boolean boolean0 = depositoryWithdrawResponse1.equals(depositoryWithdrawResponse0);
      
      //Test Result Assert
      assertTrue(boolean0);
  }

  @Test(timeout = 9000)
  public void test_equals_3()  throws Throwable  {
      //caseID:d2c9dd3e1fb8887bb5f5534c8ff6e06d
      //CoveredLines: [15, 15, 15, 15, 15, 15, 20]
      //Input_0_Object: depositoryWithdrawResponse1
      //Assert: assertTrue(method_result);
      
      DepositoryWithdrawResponse depositoryWithdrawResponse0 = new DepositoryWithdrawResponse();
      DepositoryWithdrawResponse depositoryWithdrawResponse1 = new DepositoryWithdrawResponse();
      
      //Call method: equals
      boolean boolean0 = depositoryWithdrawResponse0.equals(depositoryWithdrawResponse1);
      
      //Test Result Assert
      assertTrue(boolean0);
  }

  @Test(timeout = 9000)
  public void test_getTransactionStatus_4()  throws Throwable  {
      //caseID:8627d24259b220fca311ad5d0de5417e
      //CoveredLines: [15, 15, 15, 15, 15, 15, 20]
      //Assert: assertNull(method_result);
      
      DepositoryWithdrawResponse depositoryWithdrawResponse0 = new DepositoryWithdrawResponse();
      
      //Call method: getTransactionStatus
      String string0 = depositoryWithdrawResponse0.getTransactionStatus();
      
      //Test Result Assert
      assertNull(string0);
  }

  @Test(timeout = 9000)
  public void test_hashCode_5()  throws Throwable  {
      //caseID:d1856bf5f1ffa4beded6b8b5713a7fa8
      //CoveredLines: [15, 15, 15, 15, 15, 15, 20]
      
      DepositoryWithdrawResponse depositoryWithdrawResponse0 = new DepositoryWithdrawResponse();
      
      //Call method: hashCode
      depositoryWithdrawResponse0.hashCode();
  }

  @Test(timeout = 9000)
  public void test_setTransactionStatus_6()  throws Throwable  {
      //caseID:51774d34548f1fd88e9e419d542115a6
      //CoveredLines: [15, 15, 15, 15, 15, 15]
      //Input_0_String: 1
      
      DepositoryWithdrawResponse depositoryWithdrawResponse0 = new DepositoryWithdrawResponse();
      
      //Call method: setTransactionStatus
      depositoryWithdrawResponse0.setTransactionStatus("1");
      
      //Test Result Assert
      assertNull(depositoryWithdrawResponse0.getRequestNo());
  }

  @Test(timeout = 9000)
  public void test_toString_7()  throws Throwable  {
      //caseID:62ae9158873fa906a4e048fd82d13e88
      //CoveredLines: [15, 15, 15, 15, 15, 15, 20]
      //Assert: assertEquals("DepositoryWithdrawResponse(transactionStatus=null)", method_result);
      
      DepositoryWithdrawResponse depositoryWithdrawResponse0 = new DepositoryWithdrawResponse();
      
      //Call method: toString
      String string0 = depositoryWithdrawResponse0.toString();
      
      //Test Result Assert
      assertEquals("DepositoryWithdrawResponse(transactionStatus=null)", string0);
  }
}
