spring:
  servlet:
    multipart:
      max-file-size: 3MB

# -Denv=dev -Dapollo.cluster=DEFAULT -Dserver.port=53050
app:
  id: consumer-service
apollo:
  meta: http://192.168.158.162:8080
  bootstrap:
    enabled: true
    eagerLoad:
      enabled: true
    namespaces: application,micro_service.spring-boot-druid,micro_service.spring-boot-http,micro_service.spring-eureka,micro_service.spring-hystrix,micro_service.spring-ribbon,micro_service.spring-boot-redis,micro_service.mybatis-plus,micro_service.spring-rocketmq

logging:
  config: classpath:log4j2-dev.xml

minio:
  appId: '76fc8986f43f488487f43dfdb3fe9c35'
  accessKey: 'JDJhJDEwJHZPTjMvcmV5OUg4RHJCTURMN3dIZWVpVktQTEY0aHlySEU1TFJPOWFKNnFTWnk4ZDFoZUVP'
  secretKey: 'JDJhJDEwJHZPTjMvcmV5OUg4RHJCTURMN3dIZWVRZE05eTRVUUwxV3RJelRKeEozNThyMGlpRDh6YjlP'
  uploadUrl: 'http://127.0.0.1:56090/minio/image'

baidu:
  appId: 23658488
  accessKey: 'h5BZdSGIcTyoDzXA6CrHLMt3'
  secretKey: 'WtcHuBscFcQhyBjvzgazebXpkgPPwvkx'
