/*
 * This file was automatically generated by SmartUnit
 */

package sut.com.wanxin.gateway.filter;

import org.junit.Test;
import static org.junit.Assert.*;
import java.lang.reflect.Method;
import com.wanxin.gateway.filter.AuthFilter;
import org.junit.runner.RunWith;
import org.smartunit.runtime.SmartRunner;
import org.smartunit.runtime.SmartRunnerParameters;

@RunWith(SmartRunner.class) @SmartRunnerParameters(mockJVMNonDeterminism = true, useVNET = true, resetStaticState = true) 
public class AuthFilter_SSTest extends AuthFilter_SSTest_scaffolding {
// allCoveredLines:[19, 39, 41, 42, 44]

  @Test(timeout = 9000)
  public void test_run_0()  throws Throwable  {
      //caseID:5f3f5ed881ef12de7cfaff6206386926
      //CoveredLines: [19, 39, 41, 42, 44]
      //Assert: assertNull(method_result);
      
      AuthFilter authFilter0 = new AuthFilter();
      
      //Call method: run
      Object object0 = authFilter0.run();
      
      //Test Result Assert
      assertNull(object0);
  }
}
