/*
 * This file was automatically generated by SmartUnit
 */

package sut.com.wanxin.transaction.common.constant;

import org.junit.Test;
import static org.junit.Assert.*;
import java.lang.reflect.Method;
import com.wanxin.transaction.common.constant.TradingStatusCode;
import org.junit.runner.RunWith;
import org.smartunit.runtime.SmartRunner;
import org.smartunit.runtime.SmartRunnerParameters;

@RunWith(SmartRunner.class) @SmartRunnerParameters(mockJVMNonDeterminism = true, useVNET = true, resetStaticState = true) 
public class TradingStatusCode_SSTest extends TradingStatusCode_SSTest_scaffolding {
// allCoveredLines:[55, 59, 60, 63, 67, 68]

  @Test(timeout = 9000)
  public void test_getCode_0()  throws Throwable  {
      //caseID:e87d4db30da846031478e193d1e63be6
      //CoveredLines: [55]
      
      TradingStatusCode tradingStatusCode0 = TradingStatusCode.STATUS_REFUNDED;
      
      //Call method: getCode
      tradingStatusCode0.getCode();
  }

  @Test(timeout = 9000)
  public void test_getDesc_1()  throws Throwable  {
      //caseID:5f6e1e3a719dac729e3ab238abcd5202
      //CoveredLines: [63]
      
      TradingStatusCode tradingStatusCode0 = TradingStatusCode.STATUS_ACCEPT;
      
      //Call method: getDesc
      tradingStatusCode0.getDesc();
  }

  @Test(timeout = 9000)
  public void test_setCode_2()  throws Throwable  {
      //caseID:4da368157fca81e37dd751341815eff9
      //CoveredLines: [59, 60]
      //Input_0_String: 1.0
      
      TradingStatusCode tradingStatusCode0 = TradingStatusCode.STATUS_REFUNDED;
      
      //Call method: setCode
      tradingStatusCode0.setCode("1.0");
  }

  @Test(timeout = 9000)
  public void test_setDesc_3()  throws Throwable  {
      //caseID:7265af331b8e53b272f1d0ddda86ec9a
      //CoveredLines: [67, 68]
      //Input_0_String: 6
      
      TradingStatusCode tradingStatusCode0 = TradingStatusCode.STATUS_ACCEPT;
      
      //Call method: setDesc
      tradingStatusCode0.setDesc("6");
  }
}
