/*
 * This file was automatically generated by SmartUnit
 */

package sut.com.wanxin.transaction;

import org.junit.Test;
import static org.junit.Assert.*;
import java.lang.reflect.Method;
import com.wanxin.transaction.TransactionServiceApplication;
import org.junit.runner.RunWith;
import org.smartunit.runtime.SmartRunner;
import org.smartunit.runtime.SmartRunnerParameters;

@RunWith(SmartRunner.class) @SmartRunnerParameters(mockJVMNonDeterminism = true, useVNET = true, resetStaticState = true) 
public class TransactionServiceApplication_SSTest extends TransactionServiceApplication_SSTest_scaffolding {
// allCoveredLines:[18]

  @Test(timeout = 9000)
  public void test_setCurrentTimeMillis_0()  throws Throwable  {
      //caseID:bcb10c50288e93680e743b7068e921bc
      //CoveredLines: [18]
      
      TransactionServiceApplication transactionServiceApplication0 = new TransactionServiceApplication();
  }
}
