/*
 * This file was automatically generated by SmartUnit
 */

package sut.com.wanxin.api.transaction.model;

import org.junit.Test;
import static org.junit.Assert.*;
import java.lang.reflect.Method;
import com.wanxin.api.transaction.model.ModifyProjectStatusDTO;
import org.junit.runner.RunWith;
import org.smartunit.runtime.SmartRunner;
import org.smartunit.runtime.SmartRunnerParameters;

@RunWith(SmartRunner.class) @SmartRunnerParameters(mockJVMNonDeterminism = true, useVNET = true, resetStaticState = true) 
public class ModifyProjectStatusDTO_SSTest extends ModifyProjectStatusDTO_SSTest_scaffolding {
// allCoveredLines:[14, 19, 23, 27, 32]

  @Test(timeout = 9000)
  public void test_equals_0()  throws Throwable  {
      //caseID:96dae9c82d8f8f4c6be146d451470e30
      //CoveredLines: [14, 14, 14, 14, 14, 14, 14, 14, 14]
      //Input_0_Object: modifyProjectStatusDTO0
      //Assert: assertTrue(method_result);
      
      ModifyProjectStatusDTO modifyProjectStatusDTO0 = new ModifyProjectStatusDTO();
      
      //Call method: equals
      boolean boolean0 = modifyProjectStatusDTO0.equals(modifyProjectStatusDTO0);
      
      //Test Result Assert
      assertTrue(boolean0);
  }

  @Test(timeout = 9000)
  public void test_equals_1()  throws Throwable  {
      //caseID:9a46c2077f483835621576a6f9371c1f
      //CoveredLines: [14, 14, 14, 14, 14, 14, 14, 14, 14]
      //Input_0_Object: )
      //Assert: assertFalse(method_result);
      
      ModifyProjectStatusDTO modifyProjectStatusDTO0 = new ModifyProjectStatusDTO();
      
      //Call method: equals
      boolean boolean0 = modifyProjectStatusDTO0.equals(")");
      
      //Test Result Assert
      assertFalse(boolean0);
  }

  @Test(timeout = 9000)
  public void test_equals_2()  throws Throwable  {
      //caseID:5792f37feffbd4d1db9821730f8f8f2e
      //CoveredLines: [14, 14, 14, 14, 14, 14, 14, 14, 14, 19, 23, 27, 32]
      //Input_0_Object: modifyProjectStatusDTO0
      //Assert: assertTrue(method_result);
      
      ModifyProjectStatusDTO modifyProjectStatusDTO0 = new ModifyProjectStatusDTO();
      ModifyProjectStatusDTO modifyProjectStatusDTO1 = new ModifyProjectStatusDTO();
      
      //Call method: equals
      boolean boolean0 = modifyProjectStatusDTO1.equals(modifyProjectStatusDTO0);
      
      //Test Result Assert
      assertTrue(boolean0);
  }

  @Test(timeout = 9000)
  public void test_equals_3()  throws Throwable  {
      //caseID:b5a3c553ebd00c520269d1b51478a683
      //CoveredLines: [14, 14, 14, 14, 14, 14, 14, 14, 14, 19, 23, 27, 32]
      //Input_0_Object: modifyProjectStatusDTO1
      //Assert: assertTrue(method_result);
      
      ModifyProjectStatusDTO modifyProjectStatusDTO0 = new ModifyProjectStatusDTO();
      ModifyProjectStatusDTO modifyProjectStatusDTO1 = new ModifyProjectStatusDTO();
      
      //Call method: equals
      boolean boolean0 = modifyProjectStatusDTO0.equals(modifyProjectStatusDTO1);
      
      //Test Result Assert
      assertTrue(boolean0);
  }

  @Test(timeout = 9000)
  public void test_hashCode_4()  throws Throwable  {
      //caseID:7c0b887e7f9a1d874c7b2a8378f86948
      //CoveredLines: [14, 14, 14, 14, 14, 14, 14, 14, 14, 19, 23, 27, 32]
      
      ModifyProjectStatusDTO modifyProjectStatusDTO0 = new ModifyProjectStatusDTO();
      
      //Call method: hashCode
      modifyProjectStatusDTO0.hashCode();
  }

  @Test(timeout = 9000)
  public void test_setId_5()  throws Throwable  {
      //caseID:a532888f312f17bda0b96ae93eb41060
      //CoveredLines: [14, 14, 14, 14, 14, 14, 14, 14, 14]
      //Input_0_Long: (-1L)
      
      ModifyProjectStatusDTO modifyProjectStatusDTO0 = new ModifyProjectStatusDTO();
      Long long0 = new Long((-1L));
      
      //Call method: setId
      modifyProjectStatusDTO0.setId(long0);
      
      //Test Result Assert
      assertNull(modifyProjectStatusDTO0.getRequestNo());
  }

  @Test(timeout = 9000)
  public void test_setProjectNo_6()  throws Throwable  {
      //caseID:eaf43357128050cbf669269cb2887a60
      //CoveredLines: [14, 14, 14, 14, 14, 14, 14, 14, 14]
      //Input_0_String: )
      
      ModifyProjectStatusDTO modifyProjectStatusDTO0 = new ModifyProjectStatusDTO();
      
      //Call method: setProjectNo
      modifyProjectStatusDTO0.setProjectNo(")");
      
      //Test Result Assert
      assertNull(modifyProjectStatusDTO0.getRequestNo());
  }

  @Test(timeout = 9000)
  public void test_setProjectStatus_7()  throws Throwable  {
      //caseID:6690a6b1a02e0439c11fae2f7d989454
      //CoveredLines: [14, 14, 14, 14, 14, 14, 14, 14, 14]
      //Input_0_String: ,v2kz8$U
      
      ModifyProjectStatusDTO modifyProjectStatusDTO0 = new ModifyProjectStatusDTO();
      
      //Call method: setProjectStatus
      modifyProjectStatusDTO0.setProjectStatus(",v2kz8$U");
      
      //Test Result Assert
      assertNull(modifyProjectStatusDTO0.getRequestNo());
  }

  @Test(timeout = 9000)
  public void test_setRequestNo_8()  throws Throwable  {
      //caseID:b4cc422162c8f2dd91c83aa46f7d7639
      //CoveredLines: [14, 14, 14, 14, 14, 14, 14, 14, 14]
      //Input_0_String: 1
      
      ModifyProjectStatusDTO modifyProjectStatusDTO0 = new ModifyProjectStatusDTO();
      
      //Call method: setRequestNo
      modifyProjectStatusDTO0.setRequestNo("1");
      
      //Test Result Assert
      assertNull(modifyProjectStatusDTO0.getId());
  }

  @Test(timeout = 9000)
  public void test_toString_9()  throws Throwable  {
      //caseID:fcf888461547586b148a14c9750c19ed
      //CoveredLines: [14, 14, 14, 14, 14, 14, 14, 14, 14, 19, 23, 27, 32]
      //Assert: assertEquals("ModifyProjectStatusDTO(requestNo=null, projectNo=null, projectStatus=null, id=null)", method_result);
      
      ModifyProjectStatusDTO modifyProjectStatusDTO0 = new ModifyProjectStatusDTO();
      
      //Call method: toString
      String string0 = modifyProjectStatusDTO0.toString();
      
      //Test Result Assert
      assertEquals("ModifyProjectStatusDTO(requestNo=null, projectNo=null, projectStatus=null, id=null)", string0);
  }
}
