/*
 * This file was automatically generated by SmartUnit
 */

package sut.com.wanxin.repayment.config;

import org.junit.Test;
import static org.junit.Assert.*;
import java.lang.reflect.Method;
import com.baomidou.mybatisplus.extension.plugins.PaginationInterceptor;
import com.baomidou.mybatisplus.extension.plugins.PerformanceInterceptor;
import com.wanxin.repayment.config.MybatisPlusConfig;
import org.junit.runner.RunWith;
import org.smartunit.runtime.SmartRunner;
import org.smartunit.runtime.SmartRunnerParameters;

@RunWith(SmartRunner.class) @SmartRunnerParameters(mockJVMNonDeterminism = true, useVNET = true, resetStaticState = true) 
public class MybatisPlusConfig_SSTest extends MybatisPlusConfig_SSTest_scaffolding {
// allCoveredLines:[22, 25, 26, 27, 32]

  @Test(timeout = 9000)
  public void test_paginationInterceptor_0()  throws Throwable  {
      //caseID:6bbf8d55ac2ca1bcb9ce9375dd579ef2
      //CoveredLines: [22, 25, 26, 27]
      //Assert: assertNotNull(method_result);
      
      MybatisPlusConfig mybatisPlusConfig0 = new MybatisPlusConfig();
      
      //Call method: paginationInterceptor
      PaginationInterceptor paginationInterceptor0 = mybatisPlusConfig0.paginationInterceptor();
      
      //Test Result Assert
      assertNotNull(paginationInterceptor0);
  }

  @Test(timeout = 9000)
  public void test_performanceInterceptor_1()  throws Throwable  {
      //caseID:520d80ad7c295cb06180caa4bf867a4b
      //CoveredLines: [22, 32]
      //Assert: assertEquals(0L, method_result.getMaxTime());
      
      MybatisPlusConfig mybatisPlusConfig0 = new MybatisPlusConfig();
      
      //Call method: performanceInterceptor
      PerformanceInterceptor performanceInterceptor0 = mybatisPlusConfig0.performanceInterceptor();
      
      //Test Result Assert
      assertEquals(0L, performanceInterceptor0.getMaxTime());
  }
}
