/*
 * This file was automatically generated by SmartUnit
 */

package sut.com.wanxin.repayment.message;

import org.junit.Test;
import static org.junit.Assert.*;
import java.lang.reflect.Method;
import static org.smartunit.shaded.org.mockito.Mockito.*;
import org.smartunit.shaded.org.mockito.ArgumentMatchers;
import com.wanxin.repayment.message.ConfirmRepaymentConsumer;
import com.wanxin.repayment.service.RepaymentService;
import org.junit.runner.RunWith;
import org.smartunit.runtime.ExecutorServiceAnswer;
import org.smartunit.runtime.PrivateAccess;
import org.smartunit.runtime.SmartRunner;
import org.smartunit.runtime.SmartRunnerParameters;
import org.smartunit.runtime.TransactionTemplateAnswer;
import org.smartunit.runtime.ViolatedAssumptionAnswer;

@RunWith(SmartRunner.class) @SmartRunnerParameters(mockJVMNonDeterminism = true, useVNET = true, resetStaticState = true) 
public class ConfirmRepaymentConsumer_SSTest extends ConfirmRepaymentConsumer_SSTest_scaffolding {
// allCoveredLines:[20, 27, 28, 29, 32, 33]

  @Test(timeout = 9000)
  public void test_onMessage_0()  throws Throwable  {
      //caseID:4d2e78ee00c44af8bf94a10d414f4daa
      //CoveredLines: [20, 27, 28, 29, 32, 33]
      //Input_0_String: {\"amount\":1.0,\"consumerId\":0,\"userNo\":\"repaymentRequest\",\"numberOfPeriods\":1,\"principal\":-1.0,\"projectNo\":\"com.wanxin.repayment.message.ConfirmRepaymentConsumer\",\"interest\":-1.0,\"repaymentStatus\":\"1.0\",\"commission\":0.0,\"id\":1,\"projectId\":-1}
      
      ConfirmRepaymentConsumer confirmRepaymentConsumer0 = new ConfirmRepaymentConsumer();
      //mock repaymentService0
      RepaymentService repaymentService0 = mock(RepaymentService.class, withSettings().defaultAnswer(new ViolatedAssumptionAnswer()).stubOnly());
      
      PrivateAccess.setVariable((Class<?>) ConfirmRepaymentConsumer.class, confirmRepaymentConsumer0, "repaymentService", (Object) repaymentService0);
      
      //Call method: onMessage
      confirmRepaymentConsumer0.onMessage("{\"amount\":1.0,\"consumerId\":0,\"userNo\":\"repaymentRequest\",\"numberOfPeriods\":1,\"principal\":-1.0,\"projectNo\":\"com.wanxin.repayment.message.ConfirmRepaymentConsumer\",\"interest\":-1.0,\"repaymentStatus\":\"1.0\",\"commission\":0.0,\"id\":1,\"projectId\":-1}");
  }
}
