/*
 * This file was automatically generated by SmartUnit
 */

package sut.com.wanxin.account.common;

import org.junit.Test;
import static org.junit.Assert.*;
import java.lang.reflect.Method;
import com.wanxin.account.common.AccountErrorCode;
import org.junit.runner.RunWith;
import org.smartunit.runtime.SmartRunner;
import org.smartunit.runtime.SmartRunnerParameters;

@RunWith(SmartRunner.class) @SmartRunnerParameters(mockJVMNonDeterminism = true, useVNET = true, resetStaticState = true) 
public class AccountErrorCode_SSTest extends AccountErrorCode_SSTest_scaffolding {
// allCoveredLines:[34, 35, 36, 39, 44, 49]

  @Test(timeout = 9000)
  public void test_getDesc_0()  throws Throwable  {
      //caseID:d55378feeb24a4934506323b643638ea
      //CoveredLines: [49]
      
      AccountErrorCode accountErrorCode0 = AccountErrorCode.E_140152;
      
      //Call method: getDesc
      accountErrorCode0.getDesc();
  }

  @Test(timeout = 9000)
  public void test_setErrorCode_1()  throws Throwable  {
      //caseID:6ab23c052071fe99ef6f9d03c336c909
      //CoveredLines: [34, 35, 39, 44]
      //Input_0_int: 2082
      
      
      //Call method: setErrorCode
      AccountErrorCode.setErrorCode(2082);
  }

  @Test(timeout = 9000)
  public void test_setErrorCode_2()  throws Throwable  {
      //caseID:4c55e9fdac253d7b0ada1ee30883b6f5
      //CoveredLines: [34, 35, 36, 44]
      //Input_0_int: 2540
      
      
      //Call method: setErrorCode
      AccountErrorCode.setErrorCode(2540);
  }
}
