/*
 * This file was automatically generated by SmartUnit
 */

package sut.com.wanxin.api.consumer.model;

import org.junit.Test;
import static org.junit.Assert.*;
import java.lang.reflect.Method;
import com.wanxin.api.consumer.model.ConsumerRequest;
import org.junit.runner.RunWith;
import org.smartunit.runtime.SmartRunner;
import org.smartunit.runtime.SmartRunnerParameters;

@RunWith(SmartRunner.class) @SmartRunnerParameters(mockJVMNonDeterminism = true, useVNET = true, resetStaticState = true) 
public class ConsumerRequest_SSTest extends ConsumerRequest_SSTest_scaffolding {
// allCoveredLines:[12, 17, 20, 23, 26, 29, 32, 35, 38, 41, 44, 47]

  @Test(timeout = 9000)
  public void test_equals_00()  throws Throwable  {
      //caseID:f80fa66d8cd4b6364436bfa91f2744f9
      //CoveredLines: [12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12]
      //Input_0_Object: , userNo=
      //Assert: assertFalse(method_result);
      
      ConsumerRequest consumerRequest0 = new ConsumerRequest();
      
      //Call method: equals
      boolean boolean0 = consumerRequest0.equals(", userNo=");
      
      //Test Result Assert
      assertFalse(boolean0);
  }

  @Test(timeout = 9000)
  public void test_equals_01()  throws Throwable  {
      //caseID:a60f600e80298144bb7e8c57979ff2c1
      //CoveredLines: [12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12]
      //Input_0_Object: consumerRequest0
      //Assert: assertTrue(method_result);
      
      ConsumerRequest consumerRequest0 = new ConsumerRequest();
      
      //Call method: equals
      boolean boolean0 = consumerRequest0.equals(consumerRequest0);
      
      //Test Result Assert
      assertTrue(boolean0);
  }

  @Test(timeout = 9000)
  public void test_equals_02()  throws Throwable  {
      //caseID:c408f5e6a0c772c386134c6bf024c489
      //CoveredLines: [12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 17, 20, 23, 26, 29, 32, 35, 38, 41, 44, 47]
      //Input_0_Object: consumerRequest0
      //Assert: assertTrue(method_result);
      
      ConsumerRequest consumerRequest0 = new ConsumerRequest();
      ConsumerRequest consumerRequest1 = new ConsumerRequest();
      
      //Call method: equals
      boolean boolean0 = consumerRequest1.equals(consumerRequest0);
      
      //Test Result Assert
      assertTrue(boolean0);
  }

  @Test(timeout = 9000)
  public void test_equals_03()  throws Throwable  {
      //caseID:94e3d2ca7c7b7bbd877708e5ddffb5a5
      //CoveredLines: [12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 17, 20, 23, 26, 29, 32, 35, 38, 41, 44, 47]
      //Input_0_Object: consumerRequest1
      //Assert: assertTrue(method_result);
      
      ConsumerRequest consumerRequest0 = new ConsumerRequest();
      ConsumerRequest consumerRequest1 = new ConsumerRequest();
      
      //Call method: equals
      boolean boolean0 = consumerRequest0.equals(consumerRequest1);
      
      //Test Result Assert
      assertTrue(boolean0);
  }

  @Test(timeout = 9000)
  public void test_hashCode_04()  throws Throwable  {
      //caseID:52ca6b4d649c3b79061e6f439f655304
      //CoveredLines: [12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 17, 20, 23, 26, 29, 32, 35, 38, 41, 44, 47]
      
      ConsumerRequest consumerRequest0 = new ConsumerRequest();
      
      //Call method: hashCode
      consumerRequest0.hashCode();
  }

  @Test(timeout = 9000)
  public void test_setBankCode_05()  throws Throwable  {
      //caseID:4d809c10d6a053d56898aba45df04fe5
      //CoveredLines: [12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12]
      //Input_0_String: r05ISS:
      
      ConsumerRequest consumerRequest0 = new ConsumerRequest();
      
      //Call method: setBankCode
      consumerRequest0.setBankCode("r05ISS:");
      
      //Test Result Assert
      assertNull(consumerRequest0.getRole());
  }

  @Test(timeout = 9000)
  public void test_setCallbackUrl_06()  throws Throwable  {
      //caseID:ef74aaae4f5b0036a54f2fcfe12dcd5f
      //CoveredLines: [12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12]
      //Input_0_String: 
      
      ConsumerRequest consumerRequest0 = new ConsumerRequest();
      
      //Call method: setCallbackUrl
      consumerRequest0.setCallbackUrl("");
      
      //Test Result Assert
      assertNull(consumerRequest0.getIdNumber());
  }

  @Test(timeout = 9000)
  public void test_setCardNumber_07()  throws Throwable  {
      //caseID:5d2c99a3c10e3e4982a7780e2bb5e8b7
      //CoveredLines: [12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12]
      //Input_0_String: , bankCode=
      
      ConsumerRequest consumerRequest0 = new ConsumerRequest();
      
      //Call method: setCardNumber
      consumerRequest0.setCardNumber(", bankCode=");
      
      //Test Result Assert
      assertNull(consumerRequest0.getBankCode());
  }

  @Test(timeout = 9000)
  public void test_setFullname_08()  throws Throwable  {
      //caseID:8e1e8aadddbc5022feb61818415a9531
      //CoveredLines: [12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12]
      //Input_0_String: 43
      
      ConsumerRequest consumerRequest0 = new ConsumerRequest();
      
      //Call method: setFullname
      consumerRequest0.setFullname("43");
      
      //Test Result Assert
      assertNull(consumerRequest0.getUsername());
  }

  @Test(timeout = 9000)
  public void test_setId_09()  throws Throwable  {
      //caseID:16f1c645bd773e4ae1c6eb94b28df5a7
      //CoveredLines: [12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12]
      //Input_0_Long: 3138L
      
      ConsumerRequest consumerRequest0 = new ConsumerRequest();
      Long long0 = new Long(3138L);
      
      //Call method: setId
      consumerRequest0.setId(long0);
      
      //Test Result Assert
      assertNull(consumerRequest0.getUsername());
  }

  @Test(timeout = 9000)
  public void test_setIdNumber_10()  throws Throwable  {
      //caseID:37e56d53896d4d6078bdec15478bddf2
      //CoveredLines: [12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12]
      //Input_0_String: 2
      
      ConsumerRequest consumerRequest0 = new ConsumerRequest();
      
      //Call method: setIdNumber
      consumerRequest0.setIdNumber("2");
      
      //Test Result Assert
      assertNull(consumerRequest0.getRequestNo());
  }

  @Test(timeout = 9000)
  public void test_setMobile_11()  throws Throwable  {
      //caseID:63cc27da011a4efe2c557d0502f1e2f7
      //CoveredLines: [12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12]
      //Input_0_String: , bankCode=
      
      ConsumerRequest consumerRequest0 = new ConsumerRequest();
      
      //Call method: setMobile
      consumerRequest0.setMobile(", bankCode=");
      
      //Test Result Assert
      assertNull(consumerRequest0.getRole());
  }

  @Test(timeout = 9000)
  public void test_setRequestNo_12()  throws Throwable  {
      //caseID:a8d0a18ec914a3aa1bc359e459ff47d4
      //CoveredLines: [12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12]
      //Input_0_String: 1.0
      
      ConsumerRequest consumerRequest0 = new ConsumerRequest();
      
      //Call method: setRequestNo
      consumerRequest0.setRequestNo("1.0");
      
      //Test Result Assert
      assertNull(consumerRequest0.getUsername());
  }

  @Test(timeout = 9000)
  public void test_setRole_13()  throws Throwable  {
      //caseID:c6a2492404c4ab5940b60b122d9656e6
      //CoveredLines: [12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12]
      //Input_0_String: , mobile=
      
      ConsumerRequest consumerRequest0 = new ConsumerRequest();
      
      //Call method: setRole
      consumerRequest0.setRole(", mobile=");
      
      //Test Result Assert
      assertEquals(", mobile=", consumerRequest0.getRole());
  }

  @Test(timeout = 9000)
  public void test_setUserNo_14()  throws Throwable  {
      //caseID:94c226db5a9b48222b9dde53286b160e
      //CoveredLines: [12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12]
      //Input_0_String: E_BM
      
      ConsumerRequest consumerRequest0 = new ConsumerRequest();
      
      //Call method: setUserNo
      consumerRequest0.setUserNo("E_BM");
      
      //Test Result Assert
      assertNull(consumerRequest0.getRole());
  }

  @Test(timeout = 9000)
  public void test_setUsername_15()  throws Throwable  {
      //caseID:832797f6ee90f4ffc30fbf9aff3e5175
      //CoveredLines: [12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12]
      //Input_0_String: , requestNo=
      
      ConsumerRequest consumerRequest0 = new ConsumerRequest();
      
      //Call method: setUsername
      consumerRequest0.setUsername(", requestNo=");
      
      //Test Result Assert
      assertNull(consumerRequest0.getBankCode());
  }

  @Test(timeout = 9000)
  public void test_toString_16()  throws Throwable  {
      //caseID:a0262169b20f32081d60ca605b07c795
      //CoveredLines: [12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 17, 20, 23, 26, 29, 32, 35, 38, 41, 44, 47]
      //Assert: assertEquals("ConsumerRequest(id=null, username=null, fullname=null, idNumber=null, bankCode=null, cardNumber=null, mobile=null, role=null, requestNo=null, userNo=null, callbackUrl=null)", method_result);
      
      ConsumerRequest consumerRequest0 = new ConsumerRequest();
      
      //Call method: toString
      String string0 = consumerRequest0.toString();
      
      //Test Result Assert
      assertEquals("ConsumerRequest(id=null, username=null, fullname=null, idNumber=null, bankCode=null, cardNumber=null, mobile=null, role=null, requestNo=null, userNo=null, callbackUrl=null)", string0);
  }
}
