/*
 * This file was automatically generated by SmartUnit
 */

package sut.com.wanxin.api.consumer.model;

import org.junit.Test;
import static org.junit.Assert.*;
import java.lang.reflect.Method;
import com.wanxin.api.consumer.model.IdCardDTO;
import org.junit.runner.RunWith;
import org.smartunit.runtime.SmartRunner;
import org.smartunit.runtime.SmartRunnerParameters;

@RunWith(SmartRunner.class) @SmartRunnerParameters(mockJVMNonDeterminism = true, useVNET = true, resetStaticState = true) 
public class IdCardDTO_SSTest extends IdCardDTO_SSTest_scaffolding {
// allCoveredLines:[12, 16, 19, 22, 25]

  @Test(timeout = 9000)
  public void test_equals_0()  throws Throwable  {
      //caseID:c46c4028dc2f21cba50a52ed9233c285
      //CoveredLines: [12, 12, 12, 12, 12, 12, 12, 12, 12]
      //Input_0_Object: idCardDTO0
      //Assert: assertTrue(method_result);
      
      IdCardDTO idCardDTO0 = new IdCardDTO();
      
      //Call method: equals
      boolean boolean0 = idCardDTO0.equals(idCardDTO0);
      
      //Test Result Assert
      assertTrue(boolean0);
  }

  @Test(timeout = 9000)
  public void test_equals_1()  throws Throwable  {
      //caseID:32f225bdc6d88b88583597001d0783bc
      //CoveredLines: [12, 12, 12, 12, 12, 12, 12, 12, 12]
      //Input_0_Object: )
      //Assert: assertFalse(method_result);
      
      IdCardDTO idCardDTO0 = new IdCardDTO();
      
      //Call method: equals
      boolean boolean0 = idCardDTO0.equals(")");
      
      //Test Result Assert
      assertFalse(boolean0);
  }

  @Test(timeout = 9000)
  public void test_equals_2()  throws Throwable  {
      //caseID:1297ae42b02acd4f3997e2f2f7e2576c
      //CoveredLines: [12, 12, 12, 12, 12, 12, 12, 12, 12, 16, 19, 22, 25]
      //Input_0_Object: idCardDTO0
      //Assert: assertTrue(method_result);
      
      IdCardDTO idCardDTO0 = new IdCardDTO();
      IdCardDTO idCardDTO1 = new IdCardDTO();
      
      //Call method: equals
      boolean boolean0 = idCardDTO1.equals(idCardDTO0);
      
      //Test Result Assert
      assertTrue(boolean0);
  }

  @Test(timeout = 9000)
  public void test_equals_3()  throws Throwable  {
      //caseID:e1ce39bda8aaf406bfc55036b4da7370
      //CoveredLines: [12, 12, 12, 12, 12, 12, 12, 12, 12, 16, 19, 22, 25]
      //Input_0_Object: idCardDTO1
      //Assert: assertTrue(method_result);
      
      IdCardDTO idCardDTO0 = new IdCardDTO();
      IdCardDTO idCardDTO1 = new IdCardDTO();
      
      //Call method: equals
      boolean boolean0 = idCardDTO0.equals(idCardDTO1);
      
      //Test Result Assert
      assertTrue(boolean0);
  }

  @Test(timeout = 9000)
  public void test_hashCode_4()  throws Throwable  {
      //caseID:ad2e97e9b002b4e9852ace8e93420d6f
      //CoveredLines: [12, 12, 12, 12, 12, 12, 12, 12, 12, 16, 19, 22, 25]
      
      IdCardDTO idCardDTO0 = new IdCardDTO();
      
      //Call method: hashCode
      idCardDTO0.hashCode();
  }

  @Test(timeout = 9000)
  public void test_setFlag_5()  throws Throwable  {
      //caseID:d4314e4c8be1a846444bc5737b6baef3
      //CoveredLines: [12, 12, 12, 12, 12, 12, 12, 12, 12]
      //Input_0_String: 0
      
      IdCardDTO idCardDTO0 = new IdCardDTO();
      
      //Call method: setFlag
      idCardDTO0.setFlag("0");
      
      //Test Result Assert
      assertEquals("0", idCardDTO0.getFlag());
  }

  @Test(timeout = 9000)
  public void test_setIdCardAddress_6()  throws Throwable  {
      //caseID:90db02d602ac662f9de6563c5c5c54f3
      //CoveredLines: [12, 12, 12, 12, 12, 12, 12, 12, 12]
      //Input_0_String: t+|UW[iy
      
      IdCardDTO idCardDTO0 = new IdCardDTO();
      
      //Call method: setIdCardAddress
      idCardDTO0.setIdCardAddress("t+|UW[iy");
      
      //Test Result Assert
      assertNull(idCardDTO0.getIdCardNo());
  }

  @Test(timeout = 9000)
  public void test_setIdCardName_7()  throws Throwable  {
      //caseID:16f7eac756471567170e4782da3186eb
      //CoveredLines: [12, 12, 12, 12, 12, 12, 12, 12, 12]
      //Input_0_String: 
      
      IdCardDTO idCardDTO0 = new IdCardDTO();
      
      //Call method: setIdCardName
      idCardDTO0.setIdCardName("");
      
      //Test Result Assert
      assertNull(idCardDTO0.getIdCardAddress());
  }

  @Test(timeout = 9000)
  public void test_setIdCardNo_8()  throws Throwable  {
      //caseID:375408772f5ea7fb540f02ba4a594696
      //CoveredLines: [12, 12, 12, 12, 12, 12, 12, 12, 12]
      //Input_0_String: 1.0
      
      IdCardDTO idCardDTO0 = new IdCardDTO();
      
      //Call method: setIdCardNo
      idCardDTO0.setIdCardNo("1.0");
      
      //Test Result Assert
      assertEquals("1.0", idCardDTO0.getIdCardNo());
  }

  @Test(timeout = 9000)
  public void test_toString_9()  throws Throwable  {
      //caseID:1c22c3a8f1bf624adf9993b2d7e6c5bf
      //CoveredLines: [12, 12, 12, 12, 12, 12, 12, 12, 12, 16, 19, 22, 25]
      //Assert: assertEquals("IdCardDTO(flag=null, idCardNo=null, idCardName=null, idCardAddress=null)", method_result);
      
      IdCardDTO idCardDTO0 = new IdCardDTO();
      
      //Call method: toString
      String string0 = idCardDTO0.toString();
      
      //Test Result Assert
      assertEquals("IdCardDTO(flag=null, idCardNo=null, idCardName=null, idCardAddress=null)", string0);
  }
}
