version: '3.1'
services:
  logstash:
    container_name: logstash
    build: ./
    image: logstash:6.4.0
    network_mode: host
    volumes:
      - './config/logstash.yml:/usr/share/logstash/config/logstash.yml'
      - './json/wanxinp2p_project_template.json:/usr/share/logstash/config/wanxinp2p_project_template.json'
      - './sql:/usr/share/logstash/sql'
      - '/root/docker/logstash/logstash_metadata:/usr/share/logstash/config/logstash_metadata'
    environment:
      LS_JAVA_OPTS: '-Xmx256m -Xms256m'
      TZ: 'Asia/Shanghai'
