/*
 * This file was automatically generated by SmartUnit
 */

package sut.com.wanxin.consumer.interceptor;

import org.junit.Test;
import static org.junit.Assert.*;
import java.lang.reflect.Method;
import static org.smartunit.shaded.org.mockito.Mockito.*;
import org.smartunit.shaded.org.mockito.ArgumentMatchers;
import com.wanxin.consumer.interceptor.TokenInterceptor;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import org.junit.runner.RunWith;
import org.smartunit.runtime.ExecutorServiceAnswer;
import org.smartunit.runtime.SmartRunner;
import org.smartunit.runtime.SmartRunnerParameters;
import org.smartunit.runtime.TransactionTemplateAnswer;
import org.smartunit.runtime.ViolatedAssumptionAnswer;

@RunWith(SmartRunner.class) @SmartRunnerParameters(mockJVMNonDeterminism = true, useVNET = true, resetStaticState = true) 
public class TokenInterceptor_SSTest extends TokenInterceptor_SSTest_scaffolding {
// allCoveredLines:[20, 23, 24, 25, 27, 29]

  @Test(timeout = 9000)
  public void test_preHandle_0()  throws Throwable  {
      //caseID:2ee12ca67487cd7accf6c04821f65ec9
      //CoveredLines: [20, 23, 24, 29]
      //Input_0_HttpServletRequest: {}
      //Input_1_HttpServletResponse: {}
      //Input_2_Object: {}
      //Assert: assertTrue(method_result);
      
      TokenInterceptor tokenInterceptor0 = new TokenInterceptor();
      //mock httpServletRequest0
      HttpServletRequest httpServletRequest0 = mock(HttpServletRequest.class, withSettings().defaultAnswer(new ViolatedAssumptionAnswer()).stubOnly());
      //mock httpServletResponse0
      HttpServletResponse httpServletResponse0 = mock(HttpServletResponse.class, withSettings().defaultAnswer(new ViolatedAssumptionAnswer()).stubOnly());
      
      //Call method: preHandle
      boolean boolean0 = tokenInterceptor0.preHandle(httpServletRequest0, httpServletResponse0, httpServletResponse0);
      
      //Test Result Assert
      assertTrue(boolean0);
  }

  @Test(timeout = 9000)
  public void test_preHandle_1()  throws Throwable  {
      //caseID:c8b7337bb9eb16d6afb5ecdfc92dbf2e
      //CoveredLines: [20, 23, 24, 25, 27, 29]
      //Input_0_HttpServletRequest: {getParameter=\"DRo964\"}
      //Input_1_HttpServletResponse: {}
      //Input_2_Object: {}
      //Assert: assertTrue(method_result);
      
      TokenInterceptor tokenInterceptor0 = new TokenInterceptor();
      //mock httpServletRequest0
      HttpServletRequest httpServletRequest0 = mock(HttpServletRequest.class, withSettings().defaultAnswer(new ViolatedAssumptionAnswer()).stubOnly());
      doReturn("DRo964").when(httpServletRequest0).getParameter(anyString());
      //mock httpServletResponse0
      HttpServletResponse httpServletResponse0 = mock(HttpServletResponse.class, withSettings().defaultAnswer(new ViolatedAssumptionAnswer()).stubOnly());
      
      //Call method: preHandle
      boolean boolean0 = tokenInterceptor0.preHandle(httpServletRequest0, httpServletResponse0, httpServletResponse0);
      
      //Test Result Assert
      assertTrue(boolean0);
  }
}
