/*
 * This file was automatically generated by SmartUnit
 */

package sut.com.wanxin.transaction.interceptor;

import org.junit.Test;
import static org.junit.Assert.*;
import java.lang.reflect.Method;
import com.wanxin.transaction.interceptor.OpenFeignInterceptor;
import feign.RequestTemplate;
import org.junit.runner.RunWith;
import org.smartunit.runtime.SmartRunner;
import org.smartunit.runtime.SmartRunnerParameters;

@RunWith(SmartRunner.class) @SmartRunnerParameters(mockJVMNonDeterminism = true, useVNET = true, resetStaticState = true) 
public class OpenFeignInterceptor_SSTest extends OpenFeignInterceptor_SSTest_scaffolding {
// allCoveredLines:[19, 24, 27, 28]

  @Test(timeout = 9000)
  public void test_apply_0()  throws Throwable  {
      //caseID:167f0e6fe66072feb36b55158c6e69c9
      //CoveredLines: [19, 24, 27, 28]
      //Input_0_RequestTemplate: requestTemplate0
      
      OpenFeignInterceptor openFeignInterceptor0 = new OpenFeignInterceptor();
      RequestTemplate requestTemplate0 = new RequestTemplate();
      
      //Call method: apply
      openFeignInterceptor0.apply(requestTemplate0);
      
      //Test Result Assert
      assertFalse(requestTemplate0.resolved());
  }
}
