/*
 * This file was automatically generated by SmartUnit
 */

package sut.com.wanxin.transaction.config;

import org.junit.Test;
import static org.junit.Assert.*;
import java.lang.reflect.Method;
import static org.smartunit.shaded.org.mockito.Mockito.*;
import org.smartunit.shaded.org.mockito.ArgumentMatchers;
import static org.smartunit.runtime.SmartAssertions.*;
import com.wanxin.transaction.config.WebConfig;
import org.junit.runner.RunWith;
import org.smartunit.runtime.ExecutorServiceAnswer;
import org.smartunit.runtime.SmartRunner;
import org.smartunit.runtime.SmartRunnerParameters;
import org.smartunit.runtime.TransactionTemplateAnswer;
import org.smartunit.runtime.ViolatedAssumptionAnswer;
import org.springframework.web.servlet.config.annotation.InterceptorRegistration;
import org.springframework.web.servlet.config.annotation.InterceptorRegistry;
import org.springframework.web.servlet.config.annotation.ResourceHandlerRegistration;
import org.springframework.web.servlet.config.annotation.ResourceHandlerRegistry;

@RunWith(SmartRunner.class) @SmartRunnerParameters(mockJVMNonDeterminism = true, useVNET = true, resetStaticState = true) 
public class WebConfig_SSTest extends WebConfig_SSTest_scaffolding {
// allCoveredLines:[25, 33, 34, 74]

  @Test(timeout = 9000)
  public void test_addInterceptors_0()  throws Throwable  {
      //caseID:3aaf8d8cba835978c81a41dcc31ff38a
      //CoveredLines: [25, 33, 34]
      //Input_0_InterceptorRegistry: {addInterceptor=interceptorRegistration0}
      
      WebConfig webConfig0 = new WebConfig();
      //mock interceptorRegistration0
      InterceptorRegistration interceptorRegistration0 = mock(InterceptorRegistration.class, withSettings().defaultAnswer(new ViolatedAssumptionAnswer()).stubOnly());
      //mock interceptorRegistry0
      InterceptorRegistry interceptorRegistry0 = mock(InterceptorRegistry.class, withSettings().defaultAnswer(new ViolatedAssumptionAnswer()).stubOnly());
      doReturn(interceptorRegistration0).when(interceptorRegistry0).addInterceptor(any(org.springframework.web.servlet.HandlerInterceptor.class));
      
      //Call method: addInterceptors
      webConfig0.addInterceptors(interceptorRegistry0);
  }

  @Test(timeout = 9000)
  public void test_addResourceHandlers_1()  throws Throwable  {
      //caseID:486e0ed5ffbc8702c53734e48986d04a
      //CoveredLines: [25, 74]
      //Input_0_ResourceHandlerRegistry: {addResourceHandler=resourceHandlerRegistration0}
      
      WebConfig webConfig0 = new WebConfig();
      //mock resourceHandlerRegistration0
      ResourceHandlerRegistration resourceHandlerRegistration0 = mock(ResourceHandlerRegistration.class, withSettings().defaultAnswer(new ViolatedAssumptionAnswer()).stubOnly());
      //mock resourceHandlerRegistry0
      ResourceHandlerRegistry resourceHandlerRegistry0 = mock(ResourceHandlerRegistry.class, withSettings().defaultAnswer(new ViolatedAssumptionAnswer()).stubOnly());
      doReturn(resourceHandlerRegistration0).when(resourceHandlerRegistry0).addResourceHandler(any(java.lang.String[].class));
      
      //Call method: addResourceHandlers
      // Undeclared exception!
      try { 
        webConfig0.addResourceHandlers(resourceHandlerRegistry0);
      } catch(Throwable e) {
         verifyException("com.wanxin.transaction.config.WebConfig", e);
         assertEquals("java.lang.NullPointerException", e.getClass().getName());
      }
  }
}
