/*
 * This file was automatically generated by SmartUnit
 */

package sut.com.wanxin.common.util;

import org.junit.Test;
import static org.junit.Assert.*;
import java.lang.reflect.Method;
import static org.smartunit.runtime.SmartAssertions.*;
import com.wanxin.common.util.PasswordUtil;
import org.junit.runner.RunWith;
import org.smartunit.runtime.SmartRunner;
import org.smartunit.runtime.SmartRunnerParameters;

@RunWith(SmartRunner.class) @SmartRunnerParameters(mockJVMNonDeterminism = true, useVNET = true, resetStaticState = true) 
public class PasswordUtil_SSTest extends PasswordUtil_SSTest_scaffolding {
// allCoveredLines:[13, 18, 19, 20, 21, 22, 23, 24, 27, 28, 29, 30, 31, 32, 33, 34, 36, 43, 44, 45, 46, 47, 48, 59, 60, 61, 62, 63]

  @Test(timeout = 9000)
  public void test_generate_0()  throws Throwable  {
      //caseID:1055838f78fdc2dd21cefe171c146459
      //CoveredLines: [13, 18, 19, 20, 21, 22, 23, 24, 27, 28, 29, 30, 31, 32, 33, 34, 36, 59, 60, 61]
      //Input_0_String: 3
      //Assert: assertEquals("10d50ba0f50b704a0940040a90cc0cb03607307c00707d0d", method_result);
      
      PasswordUtil passwordUtil0 = new PasswordUtil();
      
      //Call method: generate
      String string0 = PasswordUtil.generate("3");
      
      //Test Result Assert
      //  // Unstable assertion: assertEquals("10d50ba0f50b704a0940040a90cc0cb03607307c00707d0d", string0);
  }

  @Test(timeout = 9000)
  public void test_md5Hex_1()  throws Throwable  {
      //caseID:862639c718737f844bb3fcaeae564f34
      //CoveredLines: [59, 60, 62, 63]
      //Input_0_String: null
      //Assert: assertNull(method_result);
      
      
      //Call method: md5Hex
      String string0 = PasswordUtil.md5Hex((String) null);
      
      //Test Result Assert
      assertNull(string0);
  }

  @Test(timeout = 9000)
  public void test_verify_2()  throws Throwable  {
      //caseID:7691166bc0316c77b56978540fbd0245
      //CoveredLines: [13, 43, 44, 45, 46, 47, 48]
      //Input_0_String: 1
      //Input_1_String: 1.0
      
      PasswordUtil passwordUtil0 = new PasswordUtil();
      
      //Call method: verify
      // Undeclared exception!
      try { 
        PasswordUtil.verify("1", "1.0");
      } catch(Throwable e) {
         assertEquals("java.lang.StringIndexOutOfBoundsException", e.getClass().getName());
         assertEquals("String index out of range: 3", e.getMessage());
      }
  }
}
