/*
 * This file was automatically generated by SmartUnit
 */

package sut.com.wanxin.discover;

import org.junit.Test;
import static org.junit.Assert.*;
import java.lang.reflect.Method;
import com.wanxin.discover.DiscoverServerApplication;
import org.junit.runner.RunWith;
import org.smartunit.runtime.SmartRunner;
import org.smartunit.runtime.SmartRunnerParameters;

@RunWith(SmartRunner.class) @SmartRunnerParameters(mockJVMNonDeterminism = true, useVNET = true, resetStaticState = true) 
public class DiscoverServerApplication_SSTest extends DiscoverServerApplication_SSTest_scaffolding {
// allCoveredLines:[14]

  @Test(timeout = 9000)
  public void test_setCurrentTimeMillis_0()  throws Throwable  {
      //caseID:2152176183cf3fde725e15f7ee65f05b
      //CoveredLines: [14]
      
      DiscoverServerApplication discoverServerApplication0 = new DiscoverServerApplication();
  }
}
