/*
 * This file was automatically generated by SmartUnit
 */

package sut.com.wanxin.uaa.domain;

import org.junit.Test;
import static org.junit.Assert.*;
import java.lang.reflect.Method;
import static org.smartunit.shaded.org.mockito.Mockito.*;
import org.smartunit.shaded.org.mockito.ArgumentMatchers;
import com.wanxin.uaa.domain.CustomJdbcClientDetailsService;
import javax.sql.DataSource;
import org.junit.runner.RunWith;
import org.smartunit.runtime.ExecutorServiceAnswer;
import org.smartunit.runtime.SmartRunner;
import org.smartunit.runtime.SmartRunnerParameters;
import org.smartunit.runtime.TransactionTemplateAnswer;
import org.smartunit.runtime.ViolatedAssumptionAnswer;

@RunWith(SmartRunner.class) @SmartRunnerParameters(mockJVMNonDeterminism = true, useVNET = true, resetStaticState = true) 
public class CustomJdbcClientDetailsService_SSTest extends CustomJdbcClientDetailsService_SSTest_scaffolding {
// allCoveredLines:[19, 20, 21]

  @Test(timeout = 9000)
  public void test0()  throws Throwable  {
      //caseID:78ae53d8e3e9da03556c09e3bdd4862b
      //CoveredLines: [19, 20, 21]
      
      //mock dataSource0
      DataSource dataSource0 = mock(DataSource.class, withSettings().defaultAnswer(new ViolatedAssumptionAnswer()).stubOnly());
      CustomJdbcClientDetailsService customJdbcClientDetailsService0 = new CustomJdbcClientDetailsService(dataSource0);
  }
}
