/*
 * This file was automatically generated by SmartUnit
 */

package sut.com.wanxin.depository.config;

import org.junit.Test;
import static org.junit.Assert.*;
import java.lang.reflect.Method;
import com.wanxin.common.cache.Cache;
import com.wanxin.depository.config.RedisConfig;
import org.junit.runner.RunWith;
import org.smartunit.runtime.SmartRunner;
import org.smartunit.runtime.SmartRunnerParameters;
import org.springframework.data.redis.core.StringRedisTemplate;

@RunWith(SmartRunner.class) @SmartRunnerParameters(mockJVMNonDeterminism = true, useVNET = true, resetStaticState = true) 
public class RedisConfig_SSTest extends RedisConfig_SSTest_scaffolding {
// allCoveredLines:[14, 17]

  @Test(timeout = 9000)
  public void test_cache_0()  throws Throwable  {
      //caseID:0b954f81523727631109253a0f714901
      //CoveredLines: [14, 17]
      //Input_0_StringRedisTemplate: stringRedisTemplate0
      //Assert: assertNotNull(method_result);
      
      RedisConfig redisConfig0 = new RedisConfig();
      StringRedisTemplate stringRedisTemplate0 = new StringRedisTemplate();
      
      //Call method: cache
      Cache cache0 = redisConfig0.cache(stringRedisTemplate0);
      
      //Test Result Assert
      assertNotNull(cache0);
  }
}
