/*
 * This file was automatically generated by SmartUnit
 */

package sut.com.wanxin.search.config;

import org.junit.Test;
import static org.junit.Assert.*;
import java.lang.reflect.Method;
import com.wanxin.search.config.ElasticsearchConfig;
import org.elasticsearch.client.RestHighLevelClient;
import org.junit.runner.RunWith;
import org.smartunit.runtime.PrivateAccess;
import org.smartunit.runtime.SmartRunner;
import org.smartunit.runtime.SmartRunnerParameters;

@RunWith(SmartRunner.class) @SmartRunnerParameters(mockJVMNonDeterminism = true, useVNET = true, resetStaticState = true) 
public class ElasticsearchConfig_SSTest extends ElasticsearchConfig_SSTest_scaffolding {
// allCoveredLines:[16, 23, 24, 25, 26]

  @Test(timeout = 9000)
  public void test_restHighLevelClient_0()  throws Throwable  {
      //caseID:58c5688be64c68a953d22238b2b0932a
      //CoveredLines: [16, 23, 24, 25, 26]
      //Assert: assertNotNull(method_result);
      
      ElasticsearchConfig elasticsearchConfig0 = new ElasticsearchConfig();
      
      PrivateAccess.setVariable((Class<?>) ElasticsearchConfig.class, elasticsearchConfig0, "es_host", (Object) "nH\"pU:1:wSee[#fk");
      
      //Call method: restHighLevelClient
      RestHighLevelClient restHighLevelClient0 = elasticsearchConfig0.restHighLevelClient();
      
      //Test Result Assert
      assertNotNull(restHighLevelClient0);
  }
}
